# Generated by Django 2.1.4 on 2019-10-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fibonacci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('input', models.PositiveIntegerField(blank=True, null=True)),
                ('output', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
